### ISSUE TITLE
[Setup] : Project-Setup

### ISSUE THREAD

**Issue by cmcWebCode40** [Beloved1310/Admin_Portal#1]
# Tasks.
---------------

- [x] Setup react using create-react-app 

- [x] Initialize Storybook

- [x] Setup react routing using (react-router-dom)
[react router](https://reactrouter.com/web/guides/quick-start)

- [x] Setup Styles using CSS

**Comment by cmcWebCode40** [comment]
@Beloved1310  haven't gotten feedback with respect to this taks
